### ISSUE TITLE
Can't send hashtags

### ISSUE THREAD

**Issue by DenisGorbachev** [botpress/v12#128]
First off, thanks for amazing framework! I've used Botkit and Microsoft Bot Framework before, Botpress is much better :+1: 

However, I can't send hashtags in the messages.

content.yml:
```yaml
news:
  - on: facebook
    template_type: generic
    elements:
      - title: {{{title}}}
        default_action:
          type: web_url
          url: {{{url}}}
          webview_height_ratio: compact
          webview_share_button: hide
        buttons:
          - type: postback
            title: Process
            payload: PROCESS
          - type: postback
            title: Skip
            payload: SKIP
```

index.js:
```js
event.reply('#news', {
  title: 'Saxo Bank Offers Bitcoin Exchange Traded Notes #Bitcoin',
  url: 'https://twitter.com/BTCTN/status/902225054523674626'
})
```

The "#Bitcoin" part gets chopped off. It happens because it's treated as comment by YAML parser, which runs after Mustache promptly replaces ```{{{title}}}``` with actual title.

Suggested fix:
* Load content.yml once at startup.
* Run Mustache each time before sending bloc.
