### ISSUE TITLE
array dose not work in content.yml

### ISSUE THREAD

**Issue by ghost** [botpress/v12#161]
```
goodbye:
  - text: You are leaving because of reason {{reason}}
    typing: true
  - Hope to see you back again soon! # if no other properties, you can just send a strings
  - on: telegram
    reply_markup:
      inline_keyboard:
        - - text: sdsadd
            callback_data: test

```
` Unhandled Rejection in Promise:  Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: Error: Unrecognized instruction on Web in bloc 'goodbye': { on: 'telegram',
  reply_markup: { inline_keyboard: [Array] },`
