### ISSUE TITLE
CONVO.thread.addQuestion quick reply type location getting response

### ISSUE THREAD

**Issue by ryanc200427** [botpress/v12#211]
How to get the longtitude and latitude from UMM created facebook location button?

I cant get the value from console.log(response)

##  content.yml
```
address:
-typing: true
  text: Enter your home address using Send Location
-quick_replies:
 content_type: location
 title: location
 payload: HOME_ADDRESS
```

##  index.js
```
convo.createThread('address')
    convo.threads['address'].addQuestion('#address', [
    {
      pattern: 'HOME_ADDRESS',
      callback: (response) => {
      console.log(response)
     }
    }
])
```
