### ISSUE TITLE
Setting environment variable PORT clashes with botpress and duckling

### ISSUE THREAD

**Issue by mmaybeno** [botpress/v12#825]
**Describe the bug**
Discovered using docker but I assume it is the same with a standard environment. When you specific `PORT` as an environment variable, it will set that port for the duckling server as well as botpress server port.

Duckling uses env `PORT` defined here: https://github.com/facebook/duckling/blob/master/exe/ExampleMain.hs#L54
Botpress uses the same `PORT` here:
https://github.com/botpress/botpress/blob/ebed393091885464d8f24558b18940dd56c363ae/src/bp/core/config/config-loader.ts#L55

**To Reproduce**
```
version: '3.5'

services:
  botpress:
    image: botpress/server:v12_1_5
    environment:
      - PORT=3030
    volumes:
      - ./data:/botpress/data
    ports:
      - '3030:3030'
      - '8000:8000'
```
1. Create a botpress instance using this docker-compose file. 
2. You'll notice the duckling server is not unreachable in the logs
```
botpress_1  | 12:12:56.748 Mod[nlu] Couldn't reach the Duckling server , so it will be disabled.
botpress_1  |                       For more informations (or if you want to self-host it), please check the docs at
botpress_1  |                       https://botpress.io/docs/build/nlu/#system-entities
botpress_1  |                        [Error, connect ECONNREFUSED 127.0.0.1:8000]
```
3. You'll see ports clash and botpress will start on another port.

**Expected behavior**
Botpress should but set using a different Environment variable. You already use the `BP_` with many others, so it would make sense to include it here. Also in the documentation it would be nice to create a warning that `PORT` is already used by duckling if you happen to run it locally. 

**Environment (please complete the following information):**
 - OS: 10.14.6
 - Docker: 2.1.0.3
 - Browser chrome
 - Botpress docker image: v12_1_5
