### ISSUE TITLE
[12.8.0] Cannot select a content in action dialog anymore.

### ISSUE THREAD

**Issue by Salokyn** [botpress/v12#958]
**Describe the bug**
I cannot chose a content anymore in the action dialog window since whith BP 12_8_0.

**To Reproduce**
1. Go to Flows
2. Select a standard node or create a new one
3. Add an action to it 
3. Keep 'Say something...'
4. Try to choose an existing content or to create a new one.
5. "Message" field remains empty.

**Expected behavior**
The content should be picked

**Screenshots**

**Environment (please complete the following information):**
 - OS: Docker image botpress/server:v12_8_0 (host is Ubuntu 18.04)
 - Browser : FF 74
 - Version 12.8.0

**Additional context**
If I get back to botpress/server:v12_7_2, it works as usual.

I use the following docker-compose stack:

```yml
version: "3.5"

volumes:
  data:
  db:

services:
  server:
    image: botpress/server:v12_8_0
    ports: ["3000:3000"]
    volumes:
      - data:/botpress/data
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/postgres
      - BPFS_STORAGE=database
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - db:/var/lib/postgresql/data
```
